version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-test-task
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "54322:5432"

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
